lr: 7e-4
critic_lr: 7e-4
episode_length: 400
run_dir: ./results/
log_interval: 5
use_recurrent_policy: true
use_joint_action_loss: false
use_valuenorm: true
use_adv_normalize: true

# No callbacks for now to avoid circular import issues
# We'll focus on the metric naming changes we've already implemented
callbacks: []
